version: '3'

services:
  chatgpt-web:
    image: yidadaa/chatgpt-next-web
    ports:
      - 3000:3000
    environment:
      OPENAI_API_KEY: sk-YcFZX3wlbidqL12s9fB1AdF8F589463bB57e34936dBa5523
      BASE_URL: http://azure-openai:8080
      CODE: ""
      OPENAI_API_MODEL: gpt-4
      HIDE_USER_API_KEY: 1
      HIDE_BALANCE_QUERY: 1
    depends_on:
      - azure-openai
    links:
      - azure-openai
    networks:
      - chatgpt-ns

  azure-openai:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    # volumes:
      # - ./config/config.yaml:/app/config.yaml
    environment:
      AZURE_OPENAI_ENDPOINT: https://z.kalidex.com
      AZURE_OPENAI_MODEL_MAPPER: gpt-4=gpt-4
      # AZURE_OPENAI_MODEL_MAPPER: gpt-4=gpt-4,gpt-3.5-turbo=gpt-35-turbo
      AZURE_OPENAI_API_VER: 2024-02-15-preview
    networks:
      - chatgpt-ns

networks:
  chatgpt-ns:
    driver: bridge